version: '3.5'

services: 
    api01: &api
        hostname: api01
        image: ${DOCKER_REGISTRY-}rinhabackend2024api
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
        depends_on:
        - db
        ports:
        - "8081:8080"

    api02:
        <<: *api 
        hostname: api02
        restart: always
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
        depends_on:
        - db
        ports:
        - "8082:8080"

    db:
        image: postgres
        container_name: postgress
        restart: always
        environment:
            POSTGRES_DB: rinha_backend
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
        - "5433:5432"
        volumes:
        - ./Migrations/script.sql:/docker-entrypoint-initdb.d/seu-script.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 1s
            timeout: 5s
            retries: 10

    nginx:
        image: nginx:latest
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
          - api01
          - api02
        ports:
          - "9999:9999"
        deploy:
            resources:
                limits:
                    cpus: "0.17"
                    memory: "10MB"
networks:
    default:
        driver: bridge
        name: rinha-nginx-2024q1