version: '3.5'

services: 
    api01: &api
        hostname: api01
        image: ${DOCKER_REGISTRY-}rinhabackend2024api
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
        depends_on:
        - mongodb
        ports:
        - "8081:8080"
        deploy:
            resources:
                limits:
                    cpus: "0.25"
                    memory: "75MB"

    api02:
        <<: *api 
        hostname: api02
        restart: always
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
        depends_on:
        - mongodb
        ports:
        - "8082:8080"
        
    # db:
    #     image: postgres
    #     container_name: postgress
    #     restart: always
    #     environment:
    #         POSTGRES_DB: rinha_backend
    #         POSTGRES_USER: admin
    #         POSTGRES_PASSWORD: admin
    #     ports:
    #     - "5433:5432"
    #     volumes:
    #     - ./Configs/script.sql:/docker-entrypoint-initdb.d/script.sql
    #     - ./Configs/postgres.conf:/etc/postgresql/postgresql.conf
    #     command: postgres -c config_file=/etc/postgresql/postgresql.conf
    #     deploy:
    #         resources:
    #             limits:
    #                 cpus: "0.8"
    #                 memory: "350MB"

    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_DATABASE: rinha_backend_2024
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: MyPassword123!
        ports:
          - 27017:27017
        deploy:
          resources:
            limits:
              cpus: "0.80"
              memory: "350MB"

    nginx:
        image: nginx:latest
        volumes:
          - ./Configs/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
          - api01
          - api02
        ports:
          - "9999:9999"
        deploy:
            resources:
                limits:
                    cpus: "0.2"
                    memory: "50MB"
networks:
    default:
        driver: bridge
        name: rinha-nginx-2024q1