// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RinhaBackend2024.Data;

#nullable disable

namespace RinhaBackend2024.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RinhaBackend2024.API.Domain.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Balance")
                        .HasColumnType("bigint")
                        .HasColumnName("balance");

                    b.Property<long>("Limit")
                        .HasColumnType("bigint")
                        .HasColumnName("limit");

                    b.HasKey("Id");

                    b.ToTable("clients", "public");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Balance = 0L,
                            Limit = 100000L
                        },
                        new
                        {
                            Id = 2L,
                            Balance = 0L,
                            Limit = 80000L
                        },
                        new
                        {
                            Id = 3L,
                            Balance = 0L,
                            Limit = 1000000L
                        },
                        new
                        {
                            Id = 4L,
                            Balance = 0L,
                            Limit = 10000000L
                        },
                        new
                        {
                            Id = 5L,
                            Balance = 0L,
                            Limit = 500000L
                        });
                });

            modelBuilder.Entity("RinhaBackend2024.API.Domain.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("Realized")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("realized");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<long>("Value")
                        .HasColumnType("bigint")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("transaction", "public");
                });

            modelBuilder.Entity("RinhaBackend2024.API.Domain.Transaction", b =>
                {
                    b.HasOne("RinhaBackend2024.API.Domain.Client", null)
                        .WithMany("Transations")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("RinhaBackend2024.API.Domain.Client", b =>
                {
                    b.Navigation("Transations");
                });
#pragma warning restore 612, 618
        }
    }
}
