CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240208024238_FirstMigration') THEN
    CREATE TABLE public.clients (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        "limit" bigint NOT NULL,
        balance bigint NOT NULL,
        CONSTRAINT "PK_clients" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240208024238_FirstMigration') THEN
    CREATE TABLE public.transaction (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        value bigint NOT NULL,
        type text NOT NULL,
        description text NOT NULL,
        realized timestamp with time zone NOT NULL,
        "ClientId" bigint,
        CONSTRAINT "PK_transaction" PRIMARY KEY (id),
        CONSTRAINT "FK_transaction_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES public.clients (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240208024238_FirstMigration') THEN
    CREATE INDEX "IX_transaction_ClientId" ON public.transaction ("ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240208024238_FirstMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240208024238_FirstMigration', '8.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240208031338_AddData') THEN
    ALTER TABLE public.transaction ALTER COLUMN realized TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240208031338_AddData') THEN
    INSERT INTO public.clients (id, balance, "limit")
    VALUES (1, 0, 100000);
    INSERT INTO public.clients (id, balance, "limit")
    VALUES (2, 0, 80000);
    INSERT INTO public.clients (id, balance, "limit")
    VALUES (3, 0, 1000000);
    INSERT INTO public.clients (id, balance, "limit")
    VALUES (4, 0, 10000000);
    INSERT INTO public.clients (id, balance, "limit")
    VALUES (5, 0, 500000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240208031338_AddData') THEN
    PERFORM setval(
        pg_get_serial_sequence('public.clients', 'id'),
        GREATEST(
            (SELECT MAX(id) FROM public.clients) + 1,
            nextval(pg_get_serial_sequence('public.clients', 'id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240208031338_AddData') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240208031338_AddData', '8.0.1');
    END IF;
END $EF$;
COMMIT;

